# Generated by Django 4.1.7 on 2023-03-15 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0002_category'),
        ('costomer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Breed', models.CharField(max_length=250)),
                ('Gender', models.CharField(max_length=250)),
                ('DOB', models.CharField(max_length=250)),
                ('Size', models.CharField(max_length=250)),
                ('Weight', models.CharField(max_length=250)),
                ('Health', models.CharField(max_length=250)),
                ('Location', models.CharField(max_length=250)),
                ('Photo1', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Photo2', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Contact_No', models.IntegerField()),
                ('Description', models.TextField(blank=True)),
                ('Price', models.CharField(max_length=250)),
                ('Uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='adminapp.category')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='costomer.signup')),
            ],
        ),
    ]
