# Generated by Django 4.1.7 on 2023-03-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petdetails',
            name='Contact_No',
            field=models.CharField(max_length=10),
        ),
    ]
