# Generated by Django 4.1.7 on 2023-03-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_petdetails_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petdetails',
            name='User',
        ),
    ]
