# Generated by Django 4.1.7 on 2023-03-24 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costomer', '0002_rename_password_signup_pass_word'),
        ('seller', '0003_remove_petdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='petdetails',
            name='Username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='costomer.signup'),
        ),
    ]
