# Generated by Django 4.1.7 on 2023-03-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_petdetails_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petdetails',
            old_name='DOB',
            new_name='Age',
        ),
    ]
