# Generated by Django 4.1.7 on 2023-03-18 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costomer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Password',
            new_name='Pass_word',
        ),
    ]
